config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'
  resources :visitors, only: [] do
    collection do
      get :report
      post :upload_csv
      get :query
    end
  end
  namespace :api do
    namespace :v1 do
      resources :google_search do
        collection do
          get :report
        end
      end
    end
  end
end

app/models/data_set.rb
class DataSet < ActiveRecord::Base
  has_attached_file :csv_file
  validates_attachment :csv_file, presence: true, content_type: {content_type: 'text/csv'}
end

app/models/gg_keyword.rb
require 'csv'
require 'nokogiri'
require 'open-uri'
require 'iconv' unless String.method_defined?(:encode)

class GgKeyword < ActiveRecord::Base
  include AASM
  has_one :gg_result_page, dependent: :destroy
  GOOGLE_SITE = "https://www.google.com"

  aasm column: :state, whiny_transitions: false do
    state :on, initial: true
    state :off

    event :switch do
      transitions from: [:on], to: :off
    end 
  end

  def self.create_keyword(file_path)
    CSV.foreach(file_path) do |row|
      row.each do |keyword|
        GgKeyword.create(name: keyword)
      end
    end
  end

  def process_data
    @keywords = GgKeyword.where(state: ["on"])

    @keywords.each do |keyword|
      import_data(keyword)
      keyword.switch!
    end
  end

  private
  def import_data(keyword)
    page = Nokogiri::HTML(open(GOOGLE_SITE + "/search?q=#{keyword.name}"))

    GgResultPage.create!(
      number_adword_top: page.css('#center_col').children[1].css('.ads-ad').count,
      number_adword_bottom: page.css('#center_col #bottomads').css('.ads-ad').count,
      adword_total: page.css('#center_col').children[1].css('.ads-ad').count + page.css('#center_col #bottomads').css('.ads-ad').count,
      green_url_adword_top: page.css('#center_col').children[1].css('.ads-ad cite').to_a.map{|x| x.text},
      green_url_adword_bottom: page.css('#center_col #bottomads').css('.ads-ad cite').to_a.map{|x| x.text},
      number_non_adword: page.css('#ires cite').to_a.count,
      url_non_adword: page.css('#ires cite').to_a.map{|x| x.text},
      total_links: page.css('#ires cite').count + page.css('#center_col').children[1].css('.ads-ad').count + page.css('#center_col #bottomads').css('.ads-ad').count,
      total_search: page.css('#resultStats').text.split(' ')[1].split(',').join,
      html_code: page.to_s.encode!('UTF-8', 'UTF-8', invalid: :replace),
      gg_keyword_id: keyword.id,
    )
  end
end

app/models/gg_result_page.rb
class GgResultPage < ActiveRecord::Base
  serialize :url_non_adword, Array
  serialize :green_url_adword_top, Array
  serialize :green_url_adword_bottom, Array
  belongs_to :gg_keyword
  delegate :name, to: :gg_keyword, allow_nil: true, prefix: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  before_action :validate_request_format
  respond_to :json

  def validate_request_format
    if (format = params[:format]) != 'json'
      render json: {status: false, message: t('api.v1.google_search.error.wrong_format', request_format: format)}
    end
  end
end

app/controllers/api/v1/google_search_controller.rb
class Api::V1::GoogleSearchController < Api::V1::BaseController
  def report
    respond_with(GgResultPage.joins(:gg_keyword).order("gg_keywords.name DESC").page params[:page])
  end

  def upload_csv
    #
  end

  def query
    #
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController  
  def report
    @results = GgResultPage.joins(:gg_keyword).order("gg_keywords.name DESC").page params[:page]
  end

  def upload_csv
    @data_set = DataSet.create(data_set_params)
    respond_to do |format|
      if @data_set.valid?
        UploadWorker.perform(@data_set.csv_file.path)
        format.html {redirect_to '/'}
      else
        format.js {render json: @data_set.errors, status: false}
      end
    end
  end

  def query
    
  end

  private
    def data_set_params
      params.fetch(:data_set, {}).permit(:csv_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-dark.bg-inverse
  .navbar-header
    .user-info
      = render partial: 'shared/login_signout'
  ul.nav.navbar-nav.clearfix
    li.nav-item
      button.navbar-toggler.hidden-sm-up.nav-link aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label=("Toggle navigation") data-target="#exCollapsingNavbar2" data-toggle="collapse" type="button"
        | &#9776;
  #exCollapsingNavbar2.collapse.navbar-toggleable-xs

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Google Search'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Google Search'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/shared/_login_signout.html.slim
- if user_signed_in?
  = link_to 'Logout', destroy_user_session_path, method: :delete
- else
  = link_to 'Login', new_user_session_path

app/views/shared/_sidebar.html.slim
aside.sidebar-left
  a.company-logo href="#" Nimbl
  .sidebar-links
    = link_to 'Upload File', '#', data: {target: "#myModal", toggle: "modal"}, class: 'link-blue'
    = link_to 'Report', report_visitors_url, class: 'link-red'
    = link_to 'Query', query_visitors_url, class: 'link-yellow'
= render partial: 'shared/upload_file'      

app/views/shared/_upload_file.html.slim
#myModal.modal.fade role="dialog" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button"  &times;
        h6.modal-title Upload CSV file with keywords
      .modal-body
        = form_for(@data_set=DataSet.new, url: upload_csv_visitors_path, remote: true, authenticity_token: true, method: :post) do |form|
          = form.file_field :csv_file, multipart: true, accept: 'text/csv', class: 'form-control'
          = form.submit 'Upload', class: 'btn btn-default', data: {disable_with: 'Uploading'}
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  Close

app/views/visitors/index.html.slim
.container
  .row
    = render partial: 'shared/sidebar'

app/views/visitors/query.html.slim
.row
  .col-md-12.col-xs-12
    .panel.panel-default
      .panel-heading
        | Query
      br/
      .panel-body
        .dataTable_wrapper.table-responsive
          table.table
            thead
              tr
                th Query Statement
                th Run
                th Result
            tbody
              tr
                td
                  p 
                    | How many URLs contain the word
                    = text_field_tag :query_contain_word
                    | in AdWords
                td
                  = link_to "RUN", "/", id: "run_query_contain_word", class: "btn btn-primary"
                td
                  p#result-query-contain-word
              tr
                td
                  p
                   |How many times a specific URL shows up in SEO
                td
                  = link_to "RUN", "/", id: "run_query_time_show_up_seo", class: "btn btn-danger"
                td
                  p#result-time-show-up-seo
              tr
                td    
                  p
                    |How many keywords have URLs in SEO with 2+ /’s or 1+ >
                td
                  = link_to "RUN", "/", id: "run_query_keyword_have_seo", class: "btn btn-warning"
                td
                  p#result-keyword-have-seo   

         

app/views/visitors/report.html.slim
.row
  .col-md-12.col-xs-12
    .panel.panel-default
      .panel-heading
        | Report
      br/
      .panel-body
        .dataTable_wrapper.table-responsive
          table.table
            thead
              tr
                th Number Adword Top
                th Number Adword Bottom
                th Adword Total
                th Green Url Adword Top
                th Green Url Adword Bottom
                th Number Non Adword
                th Url Non Adword
                th Total Links
                th Total Search
                th Html Code
                th Gg Keyword Name
            tbody
              - @results.each do |result|
                tr
                  td=result.number_adword_top
                  td=result.number_adword_bottom
                  td=result.adword_total
                  td=result.green_url_adword_top
                  td=result.green_url_adword_bottom
                  td=result.number_non_adword
                  td=result.url_non_adword
                  td=result.total_links
                  td=result.total_search
                  td=result.html_code
                  td=result.gg_keyword_name
          .row
            =paginate @results   